import { Divider, Flex, Heading, Image, Text } from '@chakra-ui/react';
import Head from 'next/head';
// import Image from 'next/image';
import { useEffect, useState } from 'react';

import ArticleContent from '@/components/articles/ArticleContent';

interface Post {
	attributes: {
		title: string;
		content: string;
		published_at: string;
		image: {
			data: {
				attributes: {
					url: string;
				};
			};
		};
	};
}

export default function Home() {
	const [posts, setPosts] = useState<Post[]>([]);

	useEffect(() => {
		const fetchPosts = async () => {
			const res = await fetch(
				'http://localhost:1337/api/articles?populate=image'
			);
			const { data, meta } = await res.json();
			const postArr = JSON.stringify(data);
			// const postArr = Object.entries(data);
			setPosts(data);
		};

		fetchPosts();
	}, []);

	useEffect(() => console.log(posts), [posts]);

	return (
		<>
			<Head>
				<title>Create Next App</title>
				<meta name='description' content='Generated by create next app' />
				<meta name='viewport' content='width=device-width, initial-scale=1' />
				<link rel='icon' href='/favicon.ico' />
			</Head>
			<Flex flexDir='column' gap={4} p={4}>
				<Heading>Posts</Heading>
				{posts.map((post, i) => (
					<ArticleContent
						key={i}
						title={post.attributes.title}
						content={post.attributes.content}
						image={post.attributes.image.data.attributes.url}
						date={post.attributes.published_at}
					/>
				))}
			</Flex>
		</>
	);
}
